### ISSUE TITLE
Add IncludeIf in TinyHelpers/Extensions /CollectionExtensions.cs

### ISSUE THREAD

**Issue by max1997dc** [marcominerva/TinyHelpers#167]
Is it possible to have in TinyHelpers/Extensions/CollectionExtensions.cs
not only WhereIf but also IncludeIf?
Like:

public static IQueryable<TEntity> IncludeIf<TEntity, TProperty>(
        this IQueryable<TEntity> source, bool condition,
        Expression<Func<TEntity, TProperty>> navigationPropertyPath)
        where TEntity : class
=> condition ? source.Include(navigationPropertyPath) : source;

and also for IEnumerable (like the same)?

Thanks

**Comment by DarioN1** [comment]
@max1997dc has anticipated me. 
It should be great to have a method for "ThenInclude" as well

Thanks

**Comment by marcominerva** [comment]
Then `Include` and `ThenInclude` extension methods are provided by Entity Framework Core, so `IncludeIf` and `ThenIncludeIf` should be added to this library. Does this make sense for you?

**Comment by max1997dc** [comment]
Yes please

**Comment by DarioN1** [comment]
Yes @marcominerva,  these two features can reduce a lot of conditional code while composing EF queries

**Comment by marcominerva** [comment]
@DarioN1 There is an issue with these new extension methods. The signature of `Include` is the following:

```
public static IIncludableQueryable<TEntity, TProperty> Include<TEntity, TProperty>(
    this IQueryable<TEntity> source,
    Expression<Func<TEntity, TProperty>> navigationPropertyPath)
    where TEntity : class
```

So, the return type is an `IIncludableQueryable` that contains the type of the navigation property. However, with the `IncludeIf` method, the actual return type will depend on the condition, so it can't be an `IIncludableQueryable`  (because the navigation property may have not been included). This means that `IncludeIf` cannot be chained to `ThenInclude`.
